name = "Dijkstra"
uuid = "e7a83b92-501e-4b94-a6dd-ebbcc1d264fa"
authors = ["Jukka Aho <ahojukka5@gmail.com>"]
version = "0.1.0"

[compat]
julia = "≥ 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
